server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
     druid:
      url: jdbc:mysql://localhost:3306/wfms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initial-size: 5
      maxActive: 10
      minIdle: 10
      validation-query: SELECT 'x' from dual
      test-while-idle: true
      # 空闲链接,每10秒检测一次
      time-between-eviction-runs-millis: 10000
      # 空闲链接存活180秒,就抛弃
      min-evictable-idle-time-millis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 不要加wall,该过滤用户防止sql注入,会阻塞alter语句
      filters: stat,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      useGlobalDataSourceStat: true
      filter:
        stat:
          log-slow-sql: true
  activiti:
    deployment-name: purchaseProcess

mybatis:
  mapper-locations: classpath:mybatis/*/mapper/*.xml
  config-location: classpath:mybatis-config.xml
